### ISSUE TITLE
Can't submit dat link in additions screen after android multitasking

### ISSUE THREAD

**Issue by seekr** [staltz/dat-installer#1]
Been looking forward to this! unfortunately it doesn't seem to work for me:

I took a screengrab of me trying to navigate to a dat:// link and failing: https://www.youtube.com/watch?v=0r9dztXD698

I also tried a dat://*.hasbase.io link

**Comment by staltz** [comment]
Okay, the screengrab (very useful!) gives me an idea what might be going on. Thanks!

`dat://*.hashbase.io` links certainly won't work for now, though.

**Comment by seekr** [comment]
Do clarify, my first attemp

**Comment by staltz** [comment]
Fixed! https://github.com/staltz/dat-installer/releases/tag/1.0.1

Can you try it out?

**Comment by acailly** [comment]
I had the same issue and this version works 😃
