### ISSUE TITLE
Ability to "Follow" app lists

### ISSUE THREAD

**Issue by obedm503** [staltz/dat-installer#16]
It would be very useful to offer the ability to follow lists of apps. This would convert `dat-installer` from a simple, but convenient, installer to a full-featured "app store". This inspired by Apptoide's "many stores" concept. If this idea sounds interesting to you, let me know.

#### Implementation
Currently, `dat-installer` only deals with archives representing apps. The archive has the apk, a readme, and any resources used by the readme (i.e. pictures). 

My proposal would extend the app to recognize both app archives and list archives. A list archive represents a list of apps. This is a generic definition on purpose. Anyone could group apps together by topic, author, or any arbitrary characteristic.

A list archive has a manifest, readme, and resources used by the readme. The manifest could look like this:
```json
{
  "name": "staltz apps",
  "readme": "/readme.md",
  "apps": [
    {
      "name": "Dat Installer",
      "icon": "/icons/dat-installer.png",
      "url": "dat://dat-installer-latest.hashbase.io"
    },
    {
      "name": "Manyverse",
      "icon": "/icons/manyverse.png",
      "url": "dat://manyverse-latest.hashbase.io"
    }
  ]
}
```
or
```json
{
  "name": "obedm503's favorite apps",
  "readme": "/readme.md",
  "apps": [
    {
      "name": "Usefull App",
      "icon": "/icons/useful-app.png",
      "url": "dat://8349384hf9384hf98h3f..." // not a real link
    },
    {
      "name": "Fun App",
      "icon": "/icons/fun-app.png",
      "url": "dat://8s9d8c9s8dc9s8dcsdcsd8h9..." // not a real link
    }
  ]
}
```

#### Questions
Does the app list need to include each app's name along with it's icon and url? Would it be possible to extract the app's name (maybe also the icon) from the app archive linked? I can picture a situation where an app changes its name (or icon) but wishes to keep the same link still alive. I'm really not sure if this would be possible without downloading the whole apk file.

If this was possible, the `apps` property could be simplified to a simple list of links.
```json
{
  "name": "staltz apps",
  "readme": "/readme.md",
  "apps": [
    "dat://dat-installer-latest.hashbase.io"
    "dat://manyverse-latest.hashbase.io"
  ]
}
```

#### Further improvments
Maybe an app could link back to a list archive and those are shown in a "Related apps" section for each app. This could be a `list` property in the app archive manifest that links to a list archive.
```json
{
  "convention": "1",
  "apk": "/app-release.apk",
  "readme": "/readme.md",
  "list": "dat://app-related.hashbase.io" // not a real link
}
```

**Comment by staltz** [comment]
Hi @obedm503, thanks for writing down your thoughts carefully. I'm inclined to keep Dat Installer very simple and straightforward, and also I can't spend that much time maintaining this project. I suggest you build these things in a fork of this repo, and then if your fork proves to be well built, I could consider merging it in this one, or then even declare your fork the new official repo.
