### ISSUE TITLE
Add dat.json for Beaker Browser meta

### ISSUE THREAD

**Issue by johanbove** [staltz/dat-installer#17]
When opening the dat:// link in Beaker Browser and "seeding" it, the [Dat Installer Site on Hashbase](dat://manyverse-latest.hashbase.io) currently does not show up nicely.

<img width="820" alt="Annotation 2020-03-06 121505" src="https://user-images.githubusercontent.com/922765/76079045-2b108680-5fa4-11ea-97ec-f90594607bab.png">

Ading a dat.json file could fix this.

```json
{
  "title": "Dat Installer",
  "description": "Download, install, and update Android apps through Dat"
}
```

**Comment by staltz** [comment]
I think you mean that the `dat.json` file should be added to Dat archives, right? There is nothing to be added in Dat Installer (the app itself), right?

**Comment by johanbove** [comment]
Yes, of course. Not in the app itself. I was referring to the site where you publish the apk file. When somebody opens that site with Beaker Browser, they can choose to seed it and that's where the dat.json file would give it some more meta information that shows up in the browser.
