### ISSUE TITLE
dat:// URL for Dat Installer

### ISSUE THREAD

**Issue by interfect** [staltz/dat-installer#3]
I've installed Dat Installer from the APK, and it works to install MMMMM from Dat. But when Dat Installer is updated, I won't get the update, because I installed from an APK.

Dat Installer should be able to update itself from Dat.

**Comment by tswast** [comment]
+1. I temporarily allowed installing APKs from Chrome to install this, but long term I would prefer to install updates from Day Installer itself.

**Comment by olpeh** [comment]
From discussion in SSB:

> dat://dat-installer-latest.hashbase.io
>   or
> dat://8c23f9eb1f09b5980d12bbd2150a07c8bae1b281f1f58d7ca9bef829634388d5

**Comment by staltz** [comment]
Also on the readme

**Comment by tswast** [comment]
Thanks!
